name: git to gcs

on:
  push:
    branches:
    - main
env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GITACTION_TEST_KEY_BASE64 }}
        project_id: ${{ secrets.GITACTION_TEST_PROJECT_ID }}
        export_default_credentials: true

    - name: Deploy
      run: |-
        gsutil -m rsync -R output gs://$GCS_BUCKET
