# name: GCE Connect And Execute Script

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# env:
#   PROJECT_ID: ${{ secrets.GITACTION_TEST_KEY }}
#   GCE_INSTANCE: git-action-gateway  
#   GCE_INSTANCE_ZONE: us-central1-a	
  
# jobs:
#   setup-pull-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: GCP Github Action
#         uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
#         with:
#             service_account_key: ${{ secrets.GITACTION_TEST_KEY_BASE64 }}
#             project_id: ${{ secrets.GITACTION_TEST_KEY }}
      
#       - name: Connect GCE And execute docker ps
#         run: |-
#           gcloud compute ssh "$GCE_INSTANCE" --zone "$GCE_INSTANCE_ZONE" -- 'docker ps'
