############# rollback 추가 #############


name: git to gcs
#브랜치 main으로 푸쉬
on:
  push:
    branches:
    - main
#환경변수 GCS_BUCKET 설정
env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
  F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
#job 설정
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
    #project ID, Service account key read
    - name: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.JSON_CREDENTIALS }} #json 키를 바로 연결했기 때문에 수정이 필요함
    #gcloud auth login
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    #cli 연결
    - name: 'Use gcloud CLI'
      run: 'gcloud info'
    
    - name: Deploy
      run: |-
        gsutil -m rsync -R /home/runner/work/git-action/git-action/file/ gs://$GCS_BUCKET/deploy_$HASH_TAG.file
