name: git to gcs

on:
  push:
    branches:
    - main
env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main

    - name: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.JSON_CREDENTIALS }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    
    - name: 'Use gcloud CLI'
      run: 'gcloud info'
    
    - name: Deploy
      run: |-
        gsutil -m rsync -R /home/runner/work/git-action/git-action gs://$GCS_BUCKET
