on:
  push:
    branches:
    - main
env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
  
steps:
- name: Setup - gcloud / gsutil
  uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
  with:
    service_account_key: ${{ secrets.GITACTION_TEST_KEY_BASE64 }}
    project_id: ${{ secrets.GITACTION_TEST_PROJECT_ID }}
    export_default_credentials: true

- name: Deploy
  run: |-
    gsutil -m rsync -R output gs://$GCS_BUCKET
